# gopher-rdp session config
# key value per line, # comments, blank lines ignored
# See -help for all options

# Connection
#host IP or DN
#port 3389
#user usr   # must be set for NLA
#pass pwd   # must be set for NLA 
#domain MYDOMAIN
#cookie routingtoken

# Display
#depth 32
#gui 1800x1000
#web 8080
#display 2,0
#desktop-scale 125
#device-scale 140
#no-gfx false
#no-avc false
#keyboard unicode

# Visuals
#theming true
#font-smoothing true
#wallpaper true
#window-drag false
#menu-animations false
#cursor-shadow true
#cursor-settings true
#desktop-composition true
#enable-all-visuals false

# Redirect
#no-clipboard true
#audio-out stereo,hirate,pcm,15ms   # valid values: stereo,mono,hirate,lorate,pcm or exact Hz (44100). Buffer in miliseconds
#audio-out remote # play audio through remote system speakers. If -audio-out omitted disable audio redirection completely
#audio-in mono,5ms
#drive Z:/home:ro
#serial COM3:/dev/ttyUSB0
#parallel LPT1:/dev/lp0
#printer MyPrn:/tmp/print:default
#printer MyPrn:/tmp/print:driver=Remote Desktop Easy Print:default
#printer HPNet:ipp=http://127.0.0.1:631/printers/Virtual_PDF_Printer
#printer HPNet:/tmp/print:ipp=http://127.0.0.1:631/printers/Virtual_PDF_Printer  # both: save to file and send to IPP (macos: IPP port must be listening)
#smartcard                  # bare = default socket, or smartcard /path/to/pcscd.comm (macos: support via pcsc-lite only, no CryptoTokenKit)
#usb 1234:5678              # redirect USB device by vid:pid (hex) (no macos and windows support for USB redirection)
#usb 1,5                    # redirect USB device bus.addr (decimal, e.g. 1.5)
#camera false

# Session
#admin false   # connect to admin session console
#heartbeat 10  # seconds
#auto-reconnect true
#reconnect-attempts 5
# Logging
#log ALL                 # Valid components: RDP, TPKT, NLA, X224, MCS, SEC, LIC, PDU, FASTPATH, POINTER, EGFX, CLEARCODEC, DVC, DISP, CLIPRDR, RDPSND, AUDIN, RDPDR, URBDRC, RDPECAM, BITMAP, GUI, WEB
#log-level debug         # Valid levels: error, warn, info, all/traces
#log-file gopher-rdp.log # If name omitted defaults to gopher-rdp.log in the same dir
